test workflow (#97)
* test workflow

* fix pipelines

* fix cleanup needs

* sudo

* fix dockerfile

* correct id

* new pipeline

* username in dockerfile

* test

* fix Dockerfile

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -4,16 +4,8 @@ name: CI/CD
 on:
   workflow_dispatch:
     inputs:
-      aws-account-id:
-        description: "AWS Account ID"
-        required: true
-        type: string
       aws-account-name:
         description: "AWS Account Name"
-        required: true
-        type: string
-      aws-region:
-        description: "AWS Region to launch the instance"
         required: true
         type: string
       common-name:
@@ -30,9 +22,17 @@ on:
         type: string
 
 env:
-  AWS_ACCOUNT_ID: ${{ inputs.aws-account-id }}
-  AWS_REGION: ${{ inputs.aws-region }}
   COMMON_NAME: ${{ inputs.common-name }}
+  AWS_ACCOUNT_NAME: ${{ inputs.aws-account-name }}
+  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
+  AWS_REGION: ${{ vars.AWS_REGION }}  
+  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
+  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
+  GH_ORG: KookaS
+  GH_REPO: infrastructure-modules
+  GH_BRANCH: master
+  GH_SCRIPT_PATH: .github/workflows
+  GH_INFRA_TOKEN: ${{ secrets.GH_INFRA_TOKEN }}
 
 jobs:
   build:
@@ -50,24 +50,21 @@ jobs:
   s3-env:
     name: S3 env
     runs-on: ubuntu-latest
-    environment:
-      name: ${{ inputs.aws-account-name }}
+    environment: ${{ inputs.aws-account-name }}
     env:
       BACKEND_DNS: ${{ inputs. backend-dns }}
-      BUCKET_ENV: ${{ inputs.common-name }}-env
-      ENV_FILE_NAME: ".env"
+      BRANCH: ${{ github.head_ref || github.ref_name }}
+      BUCKET_ENV: ${{ inputs.common-name }}-env # TODO: hardcoded extension here
 
     steps:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Display non-sensitive variables
+      - name: Display
         run: |
           printf " \
-          ENV_FILE_NAME = $ENV_FILE_NAME\n \
-          BACKEND_DNS = $BACKEND_DNS\n \
-          IMAGES_BUCKET = $BUCKET_ENV\n \
-          AWS_REGION = $AWS_REGION\n \
+          BRANCH = $BRANCH\n \
+          S3 file = s3://$BUCKET_ENV/$BRANCH.env\n \
           "
 
       - name: setup AWS CLI
@@ -81,8 +78,9 @@ jobs:
         run: |
           cat <<EOF > .env
           NEXT_PUBLIC_API_URL=$BACKEND_DNS
+          PORT=${{ steps.setup.outputs.PORT }}
           EOF
-          aws s3 cp .env s3://$BUCKET_ENV/$ENV_FILE_NAME
+          aws s3 cp .env s3://$BUCKET_ENV/$BRANCH.env
 
   ecr:
     name: ECR
@@ -90,53 +88,41 @@ jobs:
     environment:
       name: ${{ inputs.aws-account-name }}
     env:
-      AWS_CLI_SERVICE: ecr
-      DOCKER_FOLDER_PATH: ""
-      ECR_REPOSITORY: ${{ inputs.common-name }}
+      SCRIPT_NAME: ecr-set.sh
+      LOG_FILE: log.out
+      AWS_CLI_SERVICE: ecr # private
+      DOCKER_FOLDER_PATH: Dockerfile
+      IMAGE_TAG: "latest"
     needs: [build]
-    outputs:
-      IMAGE_TAG: ${{ steps.build-image.outputs.IMAGE_TAG }}
 
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-
-      - name: Display non-sensitive variables
+      - name: Run script
+        id: script
         run: |
-          printf " \
-          AWS_CLI_SERVICE = $AWS_CLI_SERVICE\n \
-          AWS_ACCOUNT_ID = $AWS_ACCOUNT_ID\n \
-          AWS_REGION = $AWS_REGION\n \
-          DOCKER_FOLDER_PATH = $DOCKER_FOLDER_PATH\n \
-          ECR_REPOSITORY = $ECR_REPOSITORY\n \
-          "
+          curl -L \
+            -H "Accept: application/vnd.github.v3.raw" \
+            -H "Authorization: Bearer $GH_INFRA_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/$GH_ORG/$GH_REPO/contents/$GH_SCRIPT_PATH/$SCRIPT_NAME?ref=$GH_BRANCH > $SCRIPT_NAME && chmod +x $SCRIPT_NAME
 
-      - name: setup AWS CLI
-        run: |
-          aws --version
-          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
-          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
-          aws configure set region $AWS_REGION
+          eval res=$(./$SCRIPT_NAME \
+            LOG_FILE=$LOG_FILE \
+            AWS_ACCESS_KEY=$AWS_ACCESS_KEY \
+            AWS_SECRET_KEY=$AWS_SECRET_KEY \
+            AWS_REGION=$AWS_REGION \
+            AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID \
+            COMMON_NAME=$COMMON_NAME \
+            AWS_CLI_SERVICE=ecr \
+            ECR_CREATE=false \
+            IMAGE_TAG=$IMAGE_TAG \
+            DOCKER_FOLDER_PATH=$DOCKER_FOLDER_PATH)
 
-      - name: login to ECR
-        run: |
-          if [[ $AWS_CLI_SERVICE == ecr ]]; then
-            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
-          elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
-            aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws
+          echo -e '\033[46mLOGS\033[0m'; cat $LOG_FILE
+          if [ -n "$(grep -i error $LOG_FILE)" ]; then
+            echo -e '\033[41mERRORS\033[0m'; grep -ni error $LOG_FILE | sed 's/$/\n/'; exit 10
           fi
-
-      - name: Build, tag, and push image to Amazon ECR
-        id: build-image
-        env:
-          IMAGE_TAG: "latest"
-        run: |
-          export ECR_URI=$(aws $AWS_CLI_SERVICE describe-repositories --repository-names $ECR_REPOSITORY --output text --query "repositories[].[repositoryUri]")
-          echo "ECR_URI= $ECR_URI"
-          docker build ${GITHUB_WORKSPACE}/$DOCKER_FOLDER_PATH -t $ECR_URI/$IMAGE_TAG
-          docker tag $(docker images -q $ECR_URI/$IMAGE_TAG) $ECR_URI:$IMAGE_TAG
-          docker push $ECR_URI:$IMAGE_TAG
-          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
 
   ecs:
     name: ECS
@@ -145,101 +131,31 @@ jobs:
       name: ${{ inputs.aws-account-name }}
     needs: [ecr, s3-env]
     env:
-      IMAGE_TAG: ${{ needs.ecr.outputs.IMAGE_TAG }}
+      SCRIPT_NAME: ecs-set.sh
+      LOG_FILE: log.out
       DESIRED_COUNT: ${{ inputs.task-desired-count }}
 
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-
-      - name: Display variables
+      - name: Run script
+        id: script
         run: |
-          printf " \
-          AWS_REGION = $AWS_REGION\n \
-          IMAGE_TAG = $IMAGE_TAG\n \
-          "
+          curl -L \
+            -H "Accept: application/vnd.github.v3.raw" \
+            -H "Authorization: Bearer $GH_INFRA_TOKEN" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/$GH_ORG/$GH_REPO/contents/$GH_SCRIPT_PATH/$SCRIPT_NAME?ref=$GH_BRANCH > $SCRIPT_NAME && chmod +x $SCRIPT_NAME
 
-      - name: setup AWS CLI
-        run: |
-          aws --version
-          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
-          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
-          aws configure set region $AWS_REGION
+          eval res=$(./$SCRIPT_NAME \
+            LOG_FILE=$LOG_FILE \
+            AWS_ACCESS_KEY=$AWS_ACCESS_KEY \
+            AWS_SECRET_KEY=$AWS_SECRET_KEY \
+            AWS_REGION=$AWS_REGION \
+            AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID \
+            COMMON_NAME=$COMMON_NAME)
 
-      - name: create json task definition
-        run: |
-          TASK_DEFINITION=$(aws ecs describe-task-definition \
-            --task-definition $COMMON_NAME \
-            --query 'taskDefinition' \
-            --output json)
-          cat << EOF > task_definition.json
-          {
-            "containerDefinitions": $(jq  '.containerDefinitions' <<< $TASK_DEFINITION),
-            "executionRoleArn": $(jq  '.executionRoleArn' <<< $TASK_DEFINITION),
-            "taskRoleArn": $(jq  '.taskRoleArn' <<< $TASK_DEFINITION),
-            "family": $(jq  '.family' <<< $TASK_DEFINITION),
-            "requiresCompatibilities": $(jq  '.requiresCompatibilities' <<< $TASK_DEFINITION),
-            "memory": $(jq  '.memory' <<< $TASK_DEFINITION),
-            "cpu": $(jq  '.cpu' <<< $TASK_DEFINITION)
-          }
-          EOF
-          cat task_definition.json
-
-      - name: Fill in the new image ID in the Amazon ECS task definition
-        id: task-def
-        uses: aws-actions/amazon-ecs-render-task-definition@v1
-        with:
-          task-definition: task_definition.json
-          container-name: ${{ inputs.common-name }}
-          image: ${{ needs.ecr.outputs.IMAGE_TAG }}
-
-      - name: Update service
-        run: |
-          LATEST_TASK_ARN=$(aws ecs list-task-definitions \
-            --region $AWS_REGION \
-            --family-prefix $COMMON_NAME \
-            --sort DESC \
-            --query 'taskDefinitionArns[0]' \
-            --output text)
-          aws ecs update-service \
-            --cluster $COMMON_NAME \
-            --service $COMMON_NAME \
-            --force-new-deployment \
-            --region $AWS_REGION \
-            --task-definition $LATEST_TASK_ARN \
-            --desired-count $DESIRED_COUNT \
-            --output json
-
-      - name: Wait for tasks
-        run: |
-          sleep 30
-          TASKS=$(aws ecs list-tasks \
-          --region $AWS_REGION \
-          --cluster $COMMON_NAME \
-          --query 'taskArns[]' \
-          --output text)
-          echo $TASKS
-          LATEST_TASK_DEFINITION_ARN=$(aws ecs list-task-definitions \
-          --region $AWS_REGION \
-          --family-prefix $COMMON_NAME \
-          --sort DESC \
-          --query 'taskDefinitionArns[0]' \
-          --output text)
-          for task in $TASKS; do
-              tasksDescription=$(aws ecs describe-tasks --region $AWS_REGION --cluster $COMMON_NAME --tasks $task --query 'tasks[]' --output json) || exit 1
-              echo "tasksDescription=$tasksDescription"
-              latestStatus=$(jq -r  '.[]|.lastStatus' <<< $tasksDescription)
-              taskDefinitionArn=$(jq -r  '.[]|.taskDefinitionArn' <<< $tasksDescription)
-              echo "Waiting for task $task to be RUNNING, currently $taskStatus"
-              echo "Waiting for task $task to have definition ARN $LATEST_TASK_DEFINITION_ARN, currently $taskDefinitionArn"
-              
-              while [[ $latestStatus != "RUNNING" && taskDefinitionArn != $LATEST_TASK_DEFINITION_ARN ]]
-              do
-                tasksDescription=$(aws ecs describe-tasks --region $AWS_REGION --cluster $COMMON_NAME --tasks $task --query 'tasks[]' --output json)
-                latestStatus=$(jq -r  '.[]|.lastStatus' <<< $tasksDescription)
-                taskDefinitionArn=$(jq -r  '.[]|.taskDefinitionArn' <<< $tasksDescription)
-                echo "Waiting for task $task to be RUNNING, currently $taskStatus"
-                echo "Waiting for task $task to have definition ARN $LATEST_TASK_DEFINITION_ARN, currently $taskDefinitionArn"
-                sleep 5s
-              done
-          done
+          echo -e '\033[46mLOGS\033[0m'; cat $LOG_FILE
+          if [ -n "$(grep -i error $LOG_FILE)" ]; then
+            echo -e '\033[41mERRORS\033[0m'; grep -ni error $LOG_FILE | sed 's/$/\n/'; exit 10
+          fi
